Textures lesson
FatefulStudent/HelloRender pull request #2
Opened 2021-12-28 18:03 UTC by FatefulStudent

2021-12-29 08:35 UTC, CurunirCingar commented on src/Helper/VertexData.h
> +    Vector3 Position{};
Фигурные скобки тут не нужны -- если ничего не указано, то вызовется конструктор по умолчанию
Я, кстати, до этого не встречал конструкторы с фигурными скобками -- это оказывается фича "uniform initialization" ещё с 11-го стандарта, которая позволяет сократить описание параметров, передаваемых в конструктор (типо компилятор сам выкупает что за тип надо передать в конструктор, а ты только параметры в фигурных скобках пишешь) https://mbevin.wordpress.com/2012/11/16/uniform-initialization/

2021-12-29 08:39 UTC, CurunirCingar commented on src/shaderInstance.cpp
> +const std::map<EShaderType, int> ShaderInstance::ShaderTypeToGLShaderType = {
Было бы удобнее узнавать что за тип шейдера по расширению файла

2021-12-29 08:42 UTC, CurunirCingar commented on Lessons/Textures/Ex_Textures.cpp
> +        if (nrChannels == 4)
❤️

2021-12-29 09:12 UTC, CurunirCingar requested changes
Надо пофиксить утечку (да, я знаю что сейчас программа завершается, но функция не знает об этом) и убрать лишние фигурные скобки

2021-12-29 09:12 UTC, kee-reel commented on Lessons/Textures/Ex_Textures.cpp
> +    stbi_image_free(data);
Не чистим память в случае throw

2021-12-29 09:12 UTC, kee-reel commented on Lessons/Textures/Ex_Textures.cpp
> +    unsigned int indices[] = {
Индексы тоже бы закинуть в std::vector

2021-12-29 09:12 UTC, kee-reel commented on src/Helper/VertexData.h
> +    Vector3 Position{};
Фигурные скобки тут не нужны -- если ничего не указано, то вызовется конструктор по умолчанию
Я, кстати, до этого не встречал конструкторы с фигурными скобками -- это оказывается фича "uniform initialization" ещё с 11-го стандарта, которая позволяет сократить описание параметров, передаваемых в конструктор (типо компилятор сам выкупает что за тип надо передать в конструктор, а ты только параметры в фигурных скобках пишешь) https://mbevin.wordpress.com/2012/11/16/uniform-initialization/

2021-12-29 09:12 UTC, kee-reel commented on src/shaderInstance.cpp
> +const std::map<EShaderType, int> ShaderInstance::ShaderTypeToGLShaderType = {
Было бы удобнее узнавать что за тип шейдера по расширению файла

2021-12-29 09:12 UTC, CurunirCingar commented on Lessons/Shaders/Ex_Additionals.h
>      virtual void Initialize() override;
Ты говорил по поводу code style -- можешь следовать этому https://google.github.io/styleguide/cppguide.html#Function_Names
У них есть тулза https://github.com/cpplint/cpplint

2022-01-09 13:58 UTC, kee-reel commented on src/Helper/VertexData.h
>  struct VertexData_PosColorTexture {
Может отнаследоваться от VertexData_PosColor ?

2022-01-09 13:58 UTC, kee-reel commented on src/Helper/VertexData.h
> +    static int GetIndexForPosition() { return 0; }
Очень много функций получается - может вынести эту мета-информацию в структуру, и хранить по структуре под каждое поле? Типо:
```
struct VertexDataField {
    std::size_t size;
    void* offset;
    int count;
};
...
static VertexDataField fields[] = {
    {sizeof(Vector2f), (void*)0, Vector2f::GetNumberOfComponents()},
    ...
};
...
static const VertexDataField& get_field(int index) {
    return fields[index];
}
```

2022-01-18 18:30 UTC, FatefulStudent commented on Lessons/Textures/Ex_Textures.cpp
> +    unsigned int indices[] = {
done

2022-01-18 18:31 UTC, FatefulStudent commented on src/Helper/VertexData.h
> +    Vector3 Position{};
Погоди-ка... ты уверен, что если мы создадим эту структуру на стеке, то вызовется конструктор по умолчанию?

2022-01-18 18:31 UTC, FatefulStudent commented on src/Helper/VertexData.h
>  struct VertexData_PosColorTexture {
да, наверное можно)

2022-01-18 19:41 UTC, FatefulStudent commented on src/shaderInstance.cpp
> +const std::map<EShaderType, int> ShaderInstance::ShaderTypeToGLShaderType = {
done

2022-01-18 19:42 UTC, FatefulStudent commented on Lessons/Shaders/Ex_Additionals.h
>      virtual void Initialize() override;
meh.... звучит хорошо, но как-нибудь потом. пока не важно

2022-01-18 19:42 UTC, FatefulStudent commented on Lessons/Textures/Ex_Textures.cpp
> +    stbi_image_free(data);
верно. подчистил

2022-01-18 19:43 UTC, merged

2022-01-18 19:49 UTC, FatefulStudent commented on src/Helper/VertexData.h
> +    static int GetIndexForPosition() { return 0; }
хорошая идея! но пока лень. вернусь к этому как-нибудь